// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYTH3y2lxdRBpcuIy_0HaODex12bwDWnQ',
    appId: '1:794117261159:web:150e015ca6c64f28d191c2',
    messagingSenderId: '794117261159',
    projectId: 'portfolio-contact-e578f',
    authDomain: 'portfolio-contact-e578f.firebaseapp.com',
    storageBucket: 'portfolio-contact-e578f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-zhjmAObJLvjomg8fh48XLP_rsyihgSU',
    appId: '1:794117261159:android:6466e606fe761f07d191c2',
    messagingSenderId: '794117261159',
    projectId: 'portfolio-contact-e578f',
    storageBucket: 'portfolio-contact-e578f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzI3Wz7Bf74Vjv98MfdFi66Q2Z7hC6y7Q',
    appId: '1:794117261159:ios:f6ab7c9030e9543ad191c2',
    messagingSenderId: '794117261159',
    projectId: 'portfolio-contact-e578f',
    storageBucket: 'portfolio-contact-e578f.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzI3Wz7Bf74Vjv98MfdFi66Q2Z7hC6y7Q',
    appId: '1:794117261159:ios:f6ab7c9030e9543ad191c2',
    messagingSenderId: '794117261159',
    projectId: 'portfolio-contact-e578f',
    storageBucket: 'portfolio-contact-e578f.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYTH3y2lxdRBpcuIy_0HaODex12bwDWnQ',
    appId: '1:794117261159:web:7f1056c68e521d94d191c2',
    messagingSenderId: '794117261159',
    projectId: 'portfolio-contact-e578f',
    authDomain: 'portfolio-contact-e578f.firebaseapp.com',
    storageBucket: 'portfolio-contact-e578f.firebasestorage.app',
  );
}
