// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNz32pR8If81tJWa0Hg6CoLL219qc4z84',
    appId: '1:194982231513:web:0d2f94ecd08668abd3edc8',
    messagingSenderId: '194982231513',
    projectId: 'catalystcrew-67',
    authDomain: 'catalystcrew-67.firebaseapp.com',
    storageBucket: 'catalystcrew-67.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOjsgVbX73AxKc5Q-sttN750BYWHAu9Sc',
    appId: '1:194982231513:android:51b0868890312156d3edc8',
    messagingSenderId: '194982231513',
    projectId: 'catalystcrew-67',
    storageBucket: 'catalystcrew-67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFi0o6jhQx5PNY8IhHQPUbaNeeRdNOCMU',
    appId: '1:194982231513:ios:9356d3585f83c2b9d3edc8',
    messagingSenderId: '194982231513',
    projectId: 'catalystcrew-67',
    storageBucket: 'catalystcrew-67.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFi0o6jhQx5PNY8IhHQPUbaNeeRdNOCMU',
    appId: '1:194982231513:ios:9356d3585f83c2b9d3edc8',
    messagingSenderId: '194982231513',
    projectId: 'catalystcrew-67',
    storageBucket: 'catalystcrew-67.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNz32pR8If81tJWa0Hg6CoLL219qc4z84',
    appId: '1:194982231513:web:c409e0af2c3de9f5d3edc8',
    messagingSenderId: '194982231513',
    projectId: 'catalystcrew-67',
    authDomain: 'catalystcrew-67.firebaseapp.com',
    storageBucket: 'catalystcrew-67.firebasestorage.app',
  );

}